export const homeData = [
  {
    id: 1,
    name: "Batman",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    starring: "Phan Minh Xuân",
    genres: "Action",
    tags: "Action",
    cover: "../images/home1.jpg",
    video: "../video/video.mp4",
    date: "20-Jan-2022",
  },
  {
    id: 2,
    name: "Deadpool",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks. ",
    starring: "Nguyễn Thái Bảo",
    genres: "Action",
    tags: "Action",
    cover: "../images/home2.jpg",
    video: "../video/video.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "elien",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "A woman's friendship with a new co-worker at the prison facility where she works takes a sinister turn. ",
    starring: "Bùi Duy Bảo",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Sand Dust",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Khủng long chiến đấu",
    starring: "Trần Văn An",
    genres: "Action",
    tags: "Adventures",
    cover: "../images/img/slide1.png",
    video: "../video/video.mp4",
    date: "12-Aug-2015",
  },
]
