export const homeData = [
  {
    id: 1,
    name: "Batman",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Batman is a hero",
    starring: "Phan Minh Xuan",
    genres: "Action",
    tags: "Action",
    cover: "../images/home1.jpg",
    video: "../video/video.mp4",
    date: "20-Jan-2022",
  },
  {
    id: 2,
    name: "Deadpool",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "He is a deadpool ",
    starring: "Nguyễn Thái Bảo",
    genres: "Action",
    tags: "Action",
    cover: "../images/home2.jpg",
    video: "../video/video.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "elence",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Beautiful Movie ",
    starring: "Bùi Duy Bảo",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Sand Dust",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "hahahahahaha",
    starring: "Phan Minh Xuan",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home4.jpg",
    video: "../video/video.mp4",
    date: "12-Aug-2015",
  },
]
